#!/bin/bash

function pre_pkg_setup() {
	einfo "see if we have cargo eclass"
	if [[ -n "${_CARGO_ECLASS}" ]]; then
		einfo "cargo eclass exists"
		# Show flags set
		einfo "Current BINDGEN_CFLAGS:\t${BINDGEN_CFLAGS:-no value set}"
		einfo "Current CFLAGS:\t\t${CFLAGS:-no value set}"
		einfo "Current CXXFLAGS:\t\t${CXXFLAGS:-no value set}"
		einfo "Current LDFLAGS:\t\t${LDFLAGS:-no value set}"
		einfo "Current RUSTFLAGS:\t\t${RUSTFLAGS:-no value set}"
	fi
}
