# Please consult /usr/share/portage/config/make.conf.example for a more
# detailed example.

__LLVM_SLOT="22"

FC="/usr/lib/llvm/${__LLVM_SLOT}/bin/flang"

CC="/usr/lib/llvm/${__LLVM_SLOT}/bin/clang"
CXX="/usr/lib/llvm/${__LLVM_SLOT}/bin/clang++"
CPP="/usr/lib/llvm/${__LLVM_SLOT}/bin/clang-cpp"
AR="/usr/lib/llvm/${__LLVM_SLOT}/bin/llvm-ar"
NM="/usr/lib/llvm/${__LLVM_SLOT}/bin/llvm-nm"
RANLIB="/usr/lib/llvm/${__LLVM_SLOT}/bin/llvm-ranlib"
LD="/usr/lib/llvm/${__LLVM_SLOT}/bin/ld.lld"

#ADDR2LINE="/usr/lib/llvm/${__LLVM_SLOT}/bin/llvm-addr2line"
#AS="/usr/lib/llvm/${__LLVM_SLOT}/bin/clang -c"
#CXXFILT="/usr/lib/llvm/${__LLVM_SLOT}/bin/llvm-cxxfilt"
#OBJCOPY="/usr/lib/llvm/${__LLVM_SLOT}/bin/llvm-objcopy"
#OBJDUMP="/usr/lib/llvm/${__LLVM_SLOT}/bin/llvm-objdump"
#READELF="/usr/lib/llvm/${__LLVM_SLOT}/bin/llvm-readelf"
#SIZE="/usr/lib/llvm/${__LLVM_SLOT}/bin/llvm-size"
#STRINGS="/usr/lib/llvm/${__LLVM_SLOT}/bin/llvm-strings"
#STRIP="/usr/lib/llvm/${__LLVM_SLOT}/bin/llvm-strip"

POLLY_FLAGS="-mllvm -polly -mllvm -polly-parallel -mllvm -polly-omp-backend=LLVM -mllvm -polly-num-threads=6 -mllvm -polly-vectorizer=stripmine"
GCC_LTO_FLAGS="-fgraphite-identity -floop-nest-optimize -fdevirtualize-at-ltrans -fipa-pta -fno-semantic-interposition"
WARNING_FLAGS="-Werror=odr -Werror=strict-aliasing"
COMMON_FLAGS="-march=native -O3 -pipe -flto=thin ${WARNING_FLAGS}"
#COMMON_FLAGS="-march=native -O3 -pipe"
CFLAGS="${COMMON_FLAGS}"
CXXFLAGS="${COMMON_FLAGS}"
FCFLAGS="-march=native -O3 -flto=thin -I/usr/include"
FFLAGS="-march=native -O3 -flto=thin -I/usr/include"
F77FLAGS="-march=native -O3 -flto=thin -I/usr/include"

#LDFLAGS="${COMMON_FLAGS} ${LDFLAGS}"
RUSTFLAGS="-C target-cpu=native -C strip=debuginfo -C opt-level=3"
CARGO_PROFILE_RELEASE_LTO=thin
#RUSTFLAGS="${RUSTFLAGS} -C linker=clang -C linker-plugin-lto -C link-arg=-fuse-ld=lld"
GOAMD64="v3"

# NOTE: This stage was built with the bindist USE flag enabled
MAKEOPTS="-j16 -l16"
NINJA_STATUS="[%p %f/%t] "
EMERGE_DEFAULT_OPTS="--with-bdeps=y --ask --verbose=y --keep-going\
  --deep --autounmask --autounmask-keep-masks --autounmask-write=n"
PORTDIR="/var/db/repos/gentoo"
DISTDIR="/var/cache/distfiles"
PKGDIR="/var/cache/binpkgs"
BINPKG_FORMAT="gpkg"
PORTAGE_TMPDIR="/tmp"
PORTAGE_WORKDIR_MODE="0770"
PORTAGE_LOGDIR="/var/log/portage"
PORTAGE_LOG_FILTER_FILE_CMD="bash -c \"ansifilter; exec cat\""

# This sets the language of build output to English.
# Please keep this setting intact when reporting bugs.
LC_MESSAGES=C.UTF-8

USE="-bindist -doc -debug -static-libs -test -handbook"
ACCEPT_LICENSE="*"
ACCEPT_KEYWORDS="~amd64"
L10N="en-US zh-CN en zh"
LINGUAS="en zh en_US zh_Hans zh_CN"
AUTOCLEAN="yes"

VIDEO_CARDS="intel"
ALSA_CARDS="hda-intel usb-audio"
INPUT_DEVICES="libinput"

#GENTOO_MIRRORS="https://mirrors.bfsu.edu.cn/gentoo"
GENTOO_MIRRORS="https://mirrors.tuna.tsinghua.edu.cn/gentoo"
#GENTOO_MIRRORS="https://mirrors.cqu.edu.cn/gentoo-zh"
